# -*- coding: utf-8 -*-
"""OnlineCourse.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14rcV6zPsrbVwvdq0VBkB3A38ENC1ni0b
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
data = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/OnlinecourseEngagement/online_course_engagement_data.csv')
data.head()

data['CourseCategory'].unique()

data['CourseCategory'].value_counts()

data.shape

data.describe()

data.isnull().sum()

import matplotlib.pyplot as plt
plt.figure(figsize=(10,5))
plt.bar(data['CourseCategory'],height=data['CourseCategory'].value_counts()[2])
plt.show()

plt.pie(data['CourseCategory'].value_counts(),labels=data['CourseCategory'].unique(),autopct="%.2f")
plt.show()

device = data['DeviceType'].value_counts()

plt.pie(device,labels=device.index,autopct="%.2f")
plt.show()

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

data.shape

X = data.drop(['UserID','CourseCompletion','CourseCategory'],axis=1)
y = data.CourseCompletion

X

xtrain,xtest,ytrain,ytest = train_test_split(X,y,test_size=0.25,random_state=5)

ytrain

from sklearn.linear_model import LogisticRegression
model = LogisticRegression()

model.fit(xtrain,ytrain)

ypredict = model.predict(xtest)

ypredict

accuracy_score(ytest,ypredict)

