# -*- coding: utf-8 -*-
"""Titanic.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gO3poZUUILzrPJbLauDwN0nflheucrzA
"""

import pandas as pd
titan = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Titanic/train.csv')
titan.info()

titan.isnull().sum()

titan['Embarked'].fillna(titan['Embarked'].mode()[0], inplace=True)

titan = titan.drop(columns=['Cabin'], axis=1)
titan['Age'].fillna(titan['Age'].mean(),inplace=True)

titan.isnull().sum()

titan.describe()

titan.head()

titan.replace({'Sex':{'male':0,'female':1}, 'Embarked':{'S':0,'C':1,'Q':2}}, inplace=True)

titan.head()

x = titan.drop(columns=['PassengerId','Name','Ticket','Survived'], axis=1)
y = titan['Survived']

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=2)

from sklearn.linear_model import LogisticRegression
model = LogisticRegression()

model.fit(x_train, y_train)

X_train_prediction = model.predict(x_train)

from sklearn.metrics import accuracy_score
training_data_accuracy = accuracy_score(y_train, X_train_prediction)
print('Accuracy score of training data : ', training_data_accuracy)

X_test_prediction = model.predict(x_test)
training_data_accuracy = accuracy_score(y_test, X_test_prediction)
print('Accuracy score of training data : ', training_data_accuracy)