# -*- coding: utf-8 -*-
"""real_estate.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18jFzjVcUL0CejBkaU3Ynyvnh8BIpUqLx
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
data = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Real_estate_prediction.py/Real estate.csv')
data.head()

data.info()

data.drop(columns=['No'],inplace=True)

data.head()

data.describe()

data.shape

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
model = LinearRegression()
X = data.drop(columns=['Y house price of unit area','X1 transaction date'])
y = data['Y house price of unit area']
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=2)

X_train.shape

model.fit(X_train,y_train)

y_predict = model.predict(X_test)
y_predict

from sklearn.metrics import r2_score
r2 = r2_score(y_test,y_predict)
r2

new_data = {
    'X2 house age': [36.0],
    'X3 distance to the nearest MRT station': [89.87882],
    'X4 number of convenience stores': [8],
    'X5 latitude': [24.98298],
    'X6 longitude': [121.54024]
}
new_data = pd.DataFrame(new_data)
new_data

solu = model.predict(new_data)
print(solu)